# Form implementation generated from reading ui file 'J:\DatapacksEditors\UI\Management.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(254, 241)
        self.listView = QtWidgets.QListView(Form)
        self.listView.setGeometry(QtCore.QRect(0, 0, 256, 192))
        self.listView.setObjectName("listView")
        self.download = QtWidgets.QPushButton(Form)
        self.download.setGeometry(QtCore.QRect(0, 200, 75, 24))
        self.download.setObjectName("download")
        self.done = QtWidgets.QPushButton(Form)
        self.done.setGeometry(QtCore.QRect(160, 200, 75, 24))
        self.done.setObjectName("done")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.download.setText(_translate("Form", "下载"))
        self.done.setText(_translate("Form", "确定"))
